version: '3'

services:
  mandarin:
    container_name: mandarin
    restart: always
    image: liumapp/add-mandarin-fonts-in-docker:v1.0.0
    build:
      context: .
      args:
        - LANG=C.UTF-8
    ports:
      - 8080:8080
    volumes:
      - ./fonts:/usr/share/fonts
      - ./target/add-mandarin-fonts-in-docker-v1.0.0.jar:/add-mandarin-fonts-in-docker-v1.0.0.jar
      - ./pdf:/pdf
      - ./doc:/doc
