version: '2'

services:
  mandarin:
    container_name: mandarin
    restart: always
    image: liumapp/add-mandarin-fonts-in-docker:v1.0.0
    ports:
      - 8080:8080
    volumes:
      - ./fonts:/usr/share/fonts

