version: '2'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./tmp:/fonts
    command: 
      - /bin/bash
      - -c
      - | 
          chmod -R a+w /usr/share/fonts
          mv /usr/share/fonts /fonts
          